### ISSUE TITLE
Crash when trying to set a bind

### ISSUE THREAD

**Issue by funksh0n** [Holdi601/JoystickProfiler#1]
Steps:

1. Run JoyPro.exe
2. Select 'Digital Combat Simulator'
3. Select Instance 'DCS.openbeta'
4. Load Relations Template_Johnny.rl
5. Click on any of the 'None' buttons to start binding
6. SETTINGS displayed on button and program closes with no error

OS: Windows 10 Pro N
HOTAS: Thrustmaster t.16000m Stick and Throttle

**Comment by Holdi601** [comment]
Can you open the Event Manager, go into Application and go to the .Net error and copy and paste the Details here?  Thanks :)

**Comment by funksh0n** [comment]
```
Log Name:      Application
Source:        .NET Runtime
Date:          09/03/2021 19:58:46
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-B0HQGUV
Description:
Application: JoyPro.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at JoyPro.MainWindow.AxisSet(System.Object, System.EventArgs)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(System.ComponentModel.RunWorkerCompletedEventArgs)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at JoyPro.App.Main()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-03-09T19:58:46.5279789Z" />
    <EventRecordID>1811</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-B0HQGUV</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: JoyPro.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at JoyPro.MainWindow.AxisSet(System.Object, System.EventArgs)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(System.ComponentModel.RunWorkerCompletedEventArgs)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at JoyPro.App.Main()

</Data>
  </EventData>
</Event>
```

**Comment by Holdi601** [comment]
I pushed a new version which checks for a null at that point, which i believe that to be the case. Also added a Bug collector. Next time if it crashes please upload the exception zip if possible. Please also make sure to have newest .Net installed. Just to be sure :) Thanks. Looking forward to hear back from you.

**Comment by funksh0n** [comment]
The null exception is caught and the program does not crash, but I am still unable to bind (Something went wrong.  Joyreader is null try again.)

This is a very fresh install of Windows 10 Pro N and I had not manually installed any .NET runtimes.  I just downloaded and installed the latest windowsdesktop-runtime-5.0.4-win-x64 from https://dotnet.microsoft.com/download but the issue persists.  Is there any specific version of .NET runtime you would like me to download and install?

Windows 10 Pro N is different from Windows 10 Pro in that some Microsoft applications are not pre-installed (such as Skype, Media Player), so it is possible that there are some features that JoyPr0 relies on that are not present in this version of Windows.  I faced this issue with Oculus, and had to download some additions from Microsoft to get it running.  I have no idea if this is related, but it is worth considering.

If you would like, I can download Visual Studio and clone the repo and run from there to see what is happening.  I do have some experience with debugging programs.  Are there any specific settings or configurations I would need to open the project in Visual Studio?

**Comment by Holdi601** [comment]
The project is very standart. If you install Visual studio community and clone it, you should just be able to run it and that would help greatly. You can also join discord for a more direct chat and figure out what is going wrong. I tend to believe since the Joystick detection is bust, is the SlimDX.dll in the folder? as thats the library used for reading out joystick inputs

**Comment by funksh0n** [comment]
SlimDX.dll is in the folder.

```
System.IO.FileNotFoundException
  HResult=0x8007007E
  Message=Could not load file or assembly 'SlimDX.dll' or one of its dependencies. The specified module could not be found.
  Source=JoyPro
  StackTrace:
   at JoyPro.JoystickReader..ctor(Boolean axis) in C:\Users\funksh0n\Source\Repos\JoystickProfiler\JoyPro\JoyPro\JoystickReader.cs:line 102
   at JoyPro.MainWindow.listenAxis(Object sender, EventArgs e) in C:\Users\funksh0n\Source\Repos\JoystickProfiler\JoyPro\JoyPro\MainWindow.xaml.cs:line 313
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```

SlimDX.dll is in the bin folder

![image](https://user-images.githubusercontent.com/37955287/110690786-39f3cf80-81dc-11eb-897c-51b87935f232.png)

![image](https://user-images.githubusercontent.com/37955287/110690836-4a0baf00-81dc-11eb-9ce9-607f595038e2.png)

**Comment by funksh0n** [comment]
The solution is to install [Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555)

https://github.com/Koenvh1/ets2-local-radio/issues/18#issuecomment-450047323

I suspect that SlimDX itself relies on the C++ framework.  Providing the dll is not enough, because it cannot link to the required libs.

**Comment by Holdi601** [comment]
Alright I will remember this thanks im closing the issue :)

**Comment by funksh0n** [comment]
Good stuff. It might be a good idea to update the README.md with a link to the C++ redis.

**Comment by Holdi601** [comment]
Will do
